<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!DOCTYPE devaway [
 <!ELEMENT devaway (dev*)>
   <!ATTLIST devaway date CDATA #REQUIRED>
   <!ELEMENT dev (reason)>
     <!ATTLIST dev nick CDATA #REQUIRED>
     <!ELEMENT reason (#PCDATA)>
]>

<devaway date='Tue, 06 Sep 2005 16:00:11 +0000'>
<dev nick='aaby'><reason>Busy with exam until aug. 22</reason></dev>
<dev nick='absinthe'><reason>Almost finished moving (ugh), but currently out of the country on business in Bombay/Mumbai, India.  Email is the best option, but the response time won't be awesome until I get back on July 5th.</reason></dev>
<dev nick='alexander'><reason>I'm going to be away until after exams. I will be back by late May. You won't need to contact anyone, hopefully. If you have something important, I'll probably be able to respond.</reason></dev>
<dev nick='angusyoung'><reason>Visiting clients. I'll be back Aug/13.</reason></dev>
<dev nick='axxo'><reason>email me</reason></dev>
<dev nick='battousai'><reason>Still no internet on campus. Don't say I didn't warn you. Currently hoping for a Wed Sep 5 return.</reason></dev>
<dev nick='bazik'><reason>Duty in German Army until 2006/05/31, foreign deployment in Afghanistan for International Security Assistance Force from November '05 to March '06.</reason></dev>
<dev nick='bennyc'><reason>Summer session and intern, back until mid of july</reason></dev>
<dev nick='beu'><reason>Last week(ish) at present job, might be unavailable for long periods - email me@g.o on anything that needs attention.</reason></dev>
<dev nick='centic'><reason>I have to reduce working on Gentoo-related things as my real life wants some more of my time currently...</reason></dev>
<dev nick='cyfred'><reason>permanently gone...</reason></dev>
<dev nick='dertobi123'><reason>Busy with real-life stuff, back in september. Will try to catch up all ppc-security bugs though, otherwise ask Anarchy. For German translations ask grahl.</reason></dev>
<dev nick='dholm'><reason>Moving August 13th. Status of broadband access is uncertain at the moment.</reason></dev>
<dev nick='dmwaters'><reason>moving back to florida. Won't get my stuff till Sept 2, might be back before that, depends on when i get my new machine. Jhuebel can handle major devrel issues while i'm gone, and recruiters@g.o can handle any new dev issues.</reason></dev>
<dev nick='ferringb'><reason>Busy with portage rewrite, and (soon) stable bugs.</reason></dev>
<dev nick='foser'><reason>Break until 27th of Aug, won't be reading any mail.</reason></dev>
<dev nick='geoman'><reason>New Hampshire until August 6th, Missouri until August 15th</reason></dev>
<dev nick='gregkh'><reason>Be back August 31.</reason></dev>
<dev nick='hadfield'><reason>On holidays from Friday, July 15 for about a week.</reason></dev>
<dev nick='r2d2'><reason>Away until the week of September 6th. Will be 'around' if needed until sept. then no access till I'm back.</reason></dev>
<dev nick='jforman'><reason>Moving back to school, hopefully back on early week of August 22nd.</reason></dev>
<dev nick='joem'><reason>Finished moving and getting dsl installed. Will be back no later than aug 18.</reason></dev>
<dev nick='krispykringle'><reason>Finishing classes -&gt; going to Redmond. I'm "around," but forbidden, by way of employment contract, from working on Gentoo very much.</reason></dev>
<dev nick='lewk'><reason>Working for Red Hat in Boston for the summer.  I'll be around, but not very active.</reason></dev>
<dev nick='lv'><reason>&lt;jedi mind trick&gt; I'm not really away. &lt;/jedi mind trick&gt;</reason></dev>
<dev nick='mattam'><reason>Hollidays then summer school from 15 'till 27 augut. Always working on mymaster's thesis, so don't expect much responsivness.</reason></dev>
<dev nick='mcummings'><reason>I am currently on sabatical from Gentoo and shall return in a few months time. [ 16/08/05 ]</reason></dev>
<dev nick='nerdboy'><reason>Really away to Canada and Finland until 24 August.  Please poke KingTaco or</reason></dev>
<dev nick='pclouds'><reason>Moving to Japan</reason></dev>
<dev nick='plasmaroo'><reason>Slightly limited availability for a few days.</reason></dev>
<dev nick='pylon'><reason>09/02-09/04 @ &lt;a href="http://mrmcd.metarheinmain.de/"&gt;mrmcd11b&lt;/a&gt; (Darmstadt, Hesse, Germany)</reason></dev>
<dev nick='rac'><reason>Overwhelmed by company work currently</reason></dev>
<dev nick='rajiv'><reason>visiting los angeles until wed sep 7. any devs want to meet to chat and sign keys? i will be checking email but will not be on irc.</reason></dev>
<dev nick='seemant'><reason>In Boston, without dev box.  Dev Box arrives in the middle of September, that's when I will return.  I don't check mailing lists or aliases &#45;&#45; I'm on IRC, but better to contact alternate people.</reason></dev>
<dev nick='sejo'><reason>no internet due to moving, normally 12/09 back internet :(</reason></dev>
<dev nick='slarti'><reason>Gone till 1 Aug, then gone again on the 4 Aug till 22 Aug (roughly). No mail, irc or net at all.  Recruiters -&gt; #gentoo-devrel, net-mail -&gt; #gentoo-netmail. spb has my phone if it's life threatening, but it won't be.</reason></dev>
<dev nick='solar'><reason>away moving.. as long as it takes to get done. 9-5 EST I will be reachable</reason></dev>
<dev nick='spider'><reason>Moving //  Germany from 12th to 17th ( Wave Gotik Treffen )  // 3-5 weeks before I get an ISP in my new place.</reason></dev>
<dev nick='spyderous'><reason>Wedding+honeymoon, back Sept. 5. Bug joshuabaergen/battousai about X.</reason></dev>
<dev nick='stuart'><reason>On vacation - back 1st October.</reason></dev>
<dev nick='swegener'><reason>Looking for a new job, don't expect much Gentoo work during this time. Available via IRC and mail.</reason></dev>
<dev nick='twp'><reason>Around, but generally slow reaction times at the moment: busy at work and the</reason></dev>
<dev nick='vorlon'><reason>busy with work and personal stuff; hope to have more time mid september again</reason></dev>
<dev nick='zx'><reason>Half-time now. Working on a book.</reason></dev>
<dev nick='josejx'><reason>Moved to Pittsburgh, I'll be hard to reach for the next few days until after September 6th.</reason></dev>
<dev nick='jkt'><reason>Hiking in Bulgary till 2005-09-05.</reason></dev>
<dev nick='greg_g'><reason>Away for three weeks to attend a series of conferences with limited internet access, from 8/28 to 9/18.</reason></dev>
<dev nick='xmerlin'><reason>On holidays from Monday, August 15th for about a week.</reason></dev>
<dev nick='luckyduck'><reason>Away till 2005/07/25 due to connection problems</reason></dev>
<dev nick='smithj'><reason>my laptop's motherboard fried... NEVER BUY A DELL!!! in any case, any dev can fix anything normally maintained by me. i hope to be back within a week or two, but who knows?</reason></dev>
<dev nick='deathwing00'><reason>Gone to Greece from 17 August 2005 until 7 September 2005. Please, contact 'parapente' on irc.freenode.org or enter #gentoo-el for questions regarding Greek Translations.</reason></dev>
</devaway>
